import { createElement } from 'lwc';
import CustomListView from 'c/customListView';

describe('c-custom-list-view', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-custom-list-view', {
            is: CustomListView
        });

        // Act
        document.body.appendChild(element);

        // Assert
         const div = element.shadowRoot.querySelector('dropdownTriggerClass');
         console.log('div',div)
        expect(div).toBeNull();
    });
});