public class caseHandler {
  /*  public static void CaseLimitWithinMonth(List<case> caseList){
        Integer monthNumber = Date.Today().Month();
        Integer yearNumber = Date.Today().Year();
        Integer maxCases = 10
        List<case> caseObj=[SELECT Id,CaseNumber FROM Case
                           CALENDAR_YEAR(CreatedDate) =:YearNumber and CALENDAR_MONTH(CreatedDate)=:monthnumber and CreatedById=:UserInfo.GetUserId()];
        
        if (thisMonthCaseList.Size()>=maxCases)         
            caseList[0].addError('Dear user you have exceeded the maximum number of cases allowed this month.');
    }*/
}